env:
  es2021: true
  node: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "import/extensions": "off",
  "import/no-unresolved": "off",
}
overrides: 
  - files: 
    - "**/*.test.ts"
    - "test/expect/*.ts"
    env:
      jest: true
